config/routes.rb
JackAppBase::Application.routes.draw do
  resources :words

  devise_for :users

  root :to => 'statics#home'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #

    unless user
      user = User.new
      user.roles << Role.find_or_create_by_name('Public')
    end

    can :read, :all

    if user.role? :admin
      can :manage, :all
    elsif user.role? :user
      can :read, :all
      if user.role? :moderator
        can [ :create, :update ], :all
      end
    end

    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base

  validates :name, :presence => true

  has_and_belongs_to_many :users

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_and_belongs_to_many :roles
  accepts_nested_attributes_for :roles, :allow_destroy => true

  after_create :add_default_roles

  def role?(role)
    return !!self.roles.find_by_name(role.to_s.camelize)
  end

  private

  def add_default_roles
    self.roles << Role.find_or_create_by_name('User')
  end

end

app/models/word.rb
class Word < ActiveRecord::Base
  attr_accessible :headword, :index, :language_id, :part_of_speech_id, :plural, :singular
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  check_authorization :unless => :devise_controller?

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end
end

app/controllers/statics_controller.rb
    class StaticsController < ApplicationController

      skip_authorization_check
      
      # GET /home
      def home

      end

    end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  # GET /words
  # GET /words.json
  def index
    @words = Word.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @words }
    end
  end

  # GET /words/1
  # GET /words/1.json
  def show
    @word = Word.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/new
  # GET /words/new.json
  def new
    @word = Word.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @word }
    end
  end

  # GET /words/1/edit
  def edit
    @word = Word.find(params[:id])
  end

  # POST /words
  # POST /words.json
  def create
    @word = Word.new(params[:word])

    respond_to do |format|
      if @word.save
        format.html { redirect_to @word, notice: 'Word was successfully created.' }
        format.json { render json: @word, status: :created, location: @word }
      else
        format.html { render action: "new" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /words/1
  # PUT /words/1.json
  def update
    @word = Word.find(params[:id])

    respond_to do |format|
      if @word.update_attributes(params[:word])
        format.html { redirect_to @word, notice: 'Word was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @word.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /words/1
  # DELETE /words/1.json
  def destroy
    @word = Word.find(params[:id])
    @word.destroy

    respond_to do |format|
      format.html { redirect_to words_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/layouts/application.html.haml
:erb
  <!DOCTYPE html>
%html
  %head
    %title Talk To Me!
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    .container
      .navbar.navbar-fixed-top
        .navbar-inner
          .container
            .row
              .span12
                %a.brand{:href => "#{root_path}"} Talk To Me!
                %ul.nav
                  %li= link_to 'some link', '#'
                %ul.nav.pull-right
                  %li= link_to 'Sign in', new_user_session_path unless user_signed_in?
                  %li= link_to 'Sign up', new_user_registration_path unless user_signed_in?
                  %li= link_to "Sign out #{current_user.email}", destroy_user_session_path, :method => :delete if user_signed_in?
    .container
      .row
        .span4.offset4
          - if notice
            .alert.alert-success.center
              = notice
          - if alert
            .alert.alert-error.center
              = alert
    = yield
    .container
      .row
        .span12
          %hr
          %p Footer text here.
        - if Rails.env.development?
          .span12
            = debug(params)

app/views/statics/home.html.haml
.container
  .row
    .span12
      .hero-unit
        %h1 Hello world!
      %p You are:
      %ul
        - if user_signed_in?
          %li= 'a user' if current_user.role? :user
          %li= 'a moderator' if current_user.role? :moderator
          %li= 'an admin' if current_user.role? :admin
          %p= link_to 'sign out', destroy_user_session_path, :method => :delete
        - else
          %li= 'a guest'
          %p= link_to 'sign in', new_user_session_path

app/views/words/_form.html.haml
= form_for @word do |f|
  -if @word.errors.any?
    #error_explanation
      %h2= "#{pluralize(@word.errors.count, "error")} prohibited this word from being saved:"
      %ul
        - @word.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :language_id
    = f.number_field :language_id
  .field
    = f.label :part_of_speech_id
    = f.number_field :part_of_speech_id
  .field
    = f.label :index
    = f.text_field :index
  .field
    = f.label :headword
    = f.text_field :headword
  .field
    = f.label :singular
    = f.text_field :singular
  .field
    = f.label :plural
    = f.text_field :plural
  .actions
    = f.submit 'Save'

app/views/words/edit.html.haml
%h1 Editing word

= render 'form'

= link_to 'Show', @word
\|
= link_to 'Back', words_path

app/views/words/index.html.haml
%h1 Listing words

%table
  %tr
    %th Language
    %th Part of speech
    %th Index
    %th Headword
    %th Singular
    %th Plural
    %th
    %th
    %th

  - @words.each do |word|
    %tr
      %td= word.language_id
      %td= word.part_of_speech_id
      %td= word.index
      %td= word.headword
      %td= word.singular
      %td= word.plural
      %td= link_to 'Show', word
      %td= link_to 'Edit', edit_word_path(word)
      %td= link_to 'Destroy', word, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'New Word', new_word_path

app/views/words/new.html.haml
%h1 New word

= render 'form'

= link_to 'Back', words_path

app/views/words/show.html.haml
%p#notice= notice

%p
  %b Language:
  = @word.language_id
%p
  %b Part of speech:
  = @word.part_of_speech_id
%p
  %b Index:
  = @word.index
%p
  %b Headword:
  = @word.headword
%p
  %b Singular:
  = @word.singular
%p
  %b Plural:
  = @word.plural

= link_to 'Edit', edit_word_path(@word)
\|
= link_to 'Back', words_path